##########################
### Main Config For CAA ###
##########################
#
#Notes:
#    Do not use ' or " in messages as I have not yet added support for these icons.
#   - Do not remove any lines as that will throw errors
#   - This plugin only supports Minecraft color codes. Ex) &eHello World&7!
#       - Use this link for a list of the codes: https://wiki.ess3.net/mc/
#   - If you want a message to be blank, please leave it as ''
#   - This plugin supports the following placeholders
#         - Players: %Player%
#         - Items: %Item%
#         - Money: %Money%
#         - Amount: %Amount%
#         - DisplayName: %DisplayName% (Please note that if the item does not have a display name this will return the item material instead
# If you receive an error when CAA loads, ensure that:
#   - No tabs are present: YAML only allows spaces
#   - Indents are correct: YAML hierarchy is based entirely on indentation
###########################
PluginPrefix: ''
Settings:
  #Set to 'Discord', 'Server', or 'Both'. Set it to Server if you do not have minecord, uchat, or DiscordSRV installed
  MessageSendTo: 'Server'
  #How many announcements should be allowed in each time interval
  AnnouncementAmountLimit: 5
  #How often the limit should reset so more announcements can be made (time is in minutes)
  LimiterRefreshTime: 1
  #turn to true to enable the Limiter
  UseAnnouncementLimit: false
  #Words banned from the Display Name
  BannedDisplayNameWords:
    - 'BadBones69'
  #Makes it so the item can be seen when hovering over the item
  ItemHover: true
#All server messages
Messages:
  ConfigReloaded: '&aConfig has been reloaded'
  NoPerms: '&cYou do not have permission to run this command'
  InvalidCommand: '&cThe command you entered was invalid'
  AuctionSell: '&6%Player% &eis selling %Amount% %Item% &efor &6%Money%&e.'
  AuctionBuy: '&6%Player% &ehas bought %Amount% %Item% &efor &6%Money%&e.'
  AuctionStartBid: '&6%Player% &eis auctioning %Amount% %Item% &efor &6%Money%&e.'
  AuctionBid: '&6%Player% &ehas bid %Money% on %Amount% %Item%&e.'
  AuctionWinBid: '&6%Player% &ehas won the bid for %Amount% %Item% &efor &6%Money%&e.'
Server:
  ##Can be message. title, subtitle, or action_bar
  DisplayType:
    AuctionSell: 'message'
    AuctionBuy: 'message'
    AuctionStartBid: 'message'
    AuctionBid: 'message'
    AuctionWinBid: 'message'
  EventEnabler:
    AuctionSell: true
    AuctionBuy: true
    AuctionStartBid: true
    AuctionBid: true
    AuctionWinBid: true
  TitleConfig:
    ##Time in seconds
    AuctionSell:
      FadeInTime: 3
      StayTime: 5
      FadeOutTime: 3
    AuctionBuy:
      FadeInTime: 3
      StayTime: 5
      FadeOutTime: 3
    AuctionStartBid:
      FadeInTime: 3
      StayTime: 5
      FadeOutTime: 3
    AuctionBid:
      FadeInTime: 3
      StayTime: 5
      FadeOutTime: 3
    AuctionWinBid:
      FadeInTime: 3
      StayTime: 5
      FadeOutTime: 3
##Replace the place holders with the id of the discord channel you want the messages to go to
#If you dont know how to find this, go here: https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-
Discord:
  EventEnabler:
    AuctionSell: true
    AuctionBuy: true
    AuctionStartBid: true
    AuctionBid: true
    AuctionWinBid: true
  Channels:
    AuctionSell: '265889145124159490'
    AuctionBuy: '265889145124159490'
    AuctionStartBid: '265889145124159490'
    AuctionBid: '265889145124159490'
    AuctionWinBid: '265889145124159490'
  Messages:
    AuctionSell: '&e%Player% is selling %Amount% %Item% for $%Money%'
    AuctionBuy: '&e%Player% has bought %Amount% %Item% (%DisplayName%) for $%Money%'
    AuctionStartBid: '&e%Player% is auctioning %Amount% %DisplayName% for $%Money%'
    AuctionBid: '&e%Player% has bid $%Money% on %Amount% %Item%'
    AuctionWinBid: '&e%Player% has won the bid for %Amount% %Item% for $%Money%'