##########################
### Main Config For CAA ###
##########################
#
#Notes:
#    Do not use ' or " in messages as I have not yet added support for these icons.
#   - Do not remove any lines as that will throw errors
#   - This plugin only supports Minecraft color codes. Ex) &eHello World&7!
#       - Use this link for a list of the codes: https://wiki.ess3.net/mc/
#   - If you want a message to be blank, please leave it as ''
#   - This plugin supports the following placeholders
#         - Players: %Player%
#         - Items: %Item%
#         - Money: %Money%
#         - AuctionType: %AuctionType%
#         - Amount: %Amount%
#         - DisplayName: %DisplayName% (Please note that if the item does not have a display name this will return the item material instead
# If you receive an error when CAA loads, ensure that:
#   - No tabs are present: YAML only allows spaces
#   - Indents are correct: YAML hierarchy is based entirely on indentation
###########################
PluginPrefix: '&7[&3CrazyAuctionsAnnouncer&7]&6>>'
Settings:
#Set to 'Discord', 'Server', or 'Both'. Set it to Server if you do not have minecord, uchat, or DiscordSRV installed
  MessageSendTo: 'Server'
#How many announcements should be allowed in each time interval
  AnnouncementAmountLimit: 5
#How often the limit should reset so more announcements can be made (time is in minutes)
  LimiterRefreshTime: 1
#turn to true to enable the Limiter
  UseAnnouncementLimit: false
#Words banned from the Display Name
  BannedDisplayNameWords:
    - 'BadBones69'
#All server messages
Messages:
  ConfigReloaded: '&aConfig has been reloaded'
  NoPerms: '&cYou do not have permission to run this command'
  InvalidCommand: '&cThe command you entered was invalid'
  AuctionBid: '&e%Player% has bid $%Money% on %Amount% %Item%'
  AuctionWin: '&e%Player% has bought the auction of %Amount% %Item% (%DisplayName%) for $%Money%'
  AuctionStart: '&e%Player% has started a %AuctionType% for %Amount% %Item% (%DisplayName%) for $%Money%'
  AuctionWinBid: '&e%Player% has won the bid for %Amount% %Item% for $%Money%'
Server:
##Can be message. title, subtitle, or action_bar
  DisplayType:
    AuctionBid: 'action_bar'
    AuctionWin: 'action_bar'
    AuctionStart: 'action_bar'
    AuctionWinBid: 'action_bar'
  EventEnabler:
    AuctionBid: true
    AuctionWin: true
    AuctionStart: true
    AuctionWinBid: true
  TitleConfig:
##Time in seconds
    AuctionBid:
      FadeInTime: 3
      StayTime: 5
      FadeOutTime: 3
    AuctionWin:
      FadeInTime: 3
      StayTime: 5
      FadeOutTime: 3
    AuctionStart:
      FadeInTime: 3
      StayTime: 5
      FadeOutTime: 3
    AuctionWinBid:
      FadeInTime: 3
      StayTime: 5
      FadeOutTime: 3
##Replace the place holders with the id of the discord channel you want the messages to go to
#If you dont know how to find this, go here: https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-
Discord:
  EventEnabler:
    AuctionBid: true
    AuctionWin: true
    AuctionStart: true
    AuctionWinBid: true
  Channels:
    AuctionStartServer: '265889145124159490'
    AuctionWinServer: '265889145124159490'
    AuctionBidServer: '265889145124159490'
    AuctionWinBidServer: '265889145124159490'
  Messages:
    AuctionBid: '%Player% has bid $%Money% on %Amount% %Item%'
    AuctionWin: '%Player% has bought the auction of %Amount% %Item% %DisplayName% for $%Money%'
    AuctionStart: '%Player% has started a %AuctionType% for %Amount% %Item% %DisplayName% for $%Money%'
    AuctionWinBid: '%Player% has won the bid for %Amount% %Item% for $%Money%'