main: com.diamonddagger590.caa.main.CrazyAuctionsAnnouncer
version: 2.0.0
name: CrazyAuctionsAnnouncer
api-version: 1.13
depend: [CrazyAuctions, ShowItem]
commands:
  caa:
    description: The main command for the CrazyAuctionsAnnouncer Plugin